led.setBrightness(200)
led.plot(0, 2)
basic.pause(100)
led.plot(1, 2)
basic.pause(100)
led.plot(0, 1)
led.plot(2, 2)
basic.pause(100)
led.plot(1, 1)
led.plot(3, 2)
led.plot(0, 3)
basic.pause(100)
led.plot(0, 0)
led.plot(2, 1)
led.plot(4, 2)
led.plot(1, 3)
basic.pause(100)
led.plot(1, 0)
led.plot(3, 1)
led.plot(4, 2)
led.plot(2, 3)
led.plot(0, 4)
basic.pause(100)
led.plot(2, 0)
led.plot(4, 1)
led.plot(3, 3)
led.plot(1, 4)
basic.pause(100)
led.plot(3, 0)
led.unplot(0, 2)
led.plot(4, 3)
led.plot(2, 4)
basic.pause(100)
led.plot(4, 0)
led.unplot(1, 2)
led.plot(3, 4)
basic.pause(100)
led.unplot(0, 1)
led.unplot(2, 2)
led.plot(4, 4)
basic.pause(100)
led.unplot(1, 1)
led.unplot(3, 2)
led.unplot(0, 3)
basic.pause(100)
led.unplot(0, 0)
led.unplot(2, 1)
led.unplot(4, 2)
led.unplot(1, 3)
basic.pause(100)
led.unplot(1, 0)
led.unplot(3, 1)
led.unplot(2, 3)
led.unplot(0, 4)
basic.pause(100)
led.unplot(2, 0)
led.unplot(4, 1)
led.unplot(3, 3)
led.unplot(1, 4)
basic.pause(100)
led.unplot(3, 0)
led.unplot(4, 3)
led.unplot(2, 4)
basic.pause(100)
led.unplot(4, 0)
led.unplot(3, 4)
basic.pause(100)
led.unplot(4, 4)
basic.clearScreen()
basic.forever(function () {
    while (input.buttonIsPressed(Button.B)) {
        if (input.lightLevel() == 69) {
            basic.clearScreen()
            led.setBrightness(200)
            basic.showIcon(IconNames.Yes)
        } else if (input.lightLevel() == 0) {
            for (let index = 0; index < 4; index++) {
                basic.clearScreen()
                led.setBrightness(1)
                led.plot(0, 4)
                led.plot(1, 4)
                led.plot(2, 4)
                led.plot(3, 4)
                led.plot(4, 4)
                basic.pause(50)
            }
        } else if (input.lightLevel() == 1) {
            basic.clearScreen()
            led.setBrightness(10)
            led.plot(0, 0)
            led.plot(1, 1)
            led.plot(2, 2)
            led.plot(3, 3)
            led.plot(4, 4)
            led.plot(4, 2)
            led.plot(4, 3)
            led.plot(2, 4)
            led.plot(3, 4)
        } else if (input.lightLevel() == 255) {
            basic.clearScreen()
            led.setBrightness(255)
            led.plot(2, 0)
            led.plot(3, 0)
            led.plot(4, 0)
            led.plot(3, 1)
            led.plot(4, 1)
            led.plot(2, 2)
            led.plot(4, 2)
            led.plot(1, 3)
            led.plot(0, 4)
            led.plotBrightness(0, 0, 150)
            led.plotBrightness(1, 0, 150)
            led.plotBrightness(0, 1, 150)
            led.plotBrightness(1, 1, 150)
            led.plotBrightness(2, 1, 150)
            led.plotBrightness(0, 2, 150)
            led.plotBrightness(1, 2, 150)
            led.plotBrightness(3, 2, 150)
            led.plotBrightness(0, 3, 150)
            led.plotBrightness(2, 3, 150)
            led.plotBrightness(3, 3, 150)
            led.plotBrightness(4, 3, 150)
            led.plotBrightness(1, 4, 150)
            led.plotBrightness(2, 4, 150)
            led.plotBrightness(3, 4, 150)
            led.plotBrightness(4, 4, 150)
        } else if (input.lightLevel() != 0 || input.lightLevel() != 255) {
            basic.clearScreen()
            led.setBrightness(200)
            led.plot(0, 0)
            led.plot(1, 1)
            led.plot(2, 2)
            led.plot(3, 3)
            led.plot(4, 4)
            led.plot(4, 2)
            led.plot(4, 3)
            led.plot(2, 4)
            led.plot(3, 4)
        } else if (input.lightLevel() > 69 && (input.lightLevel() != 0 || input.lightLevel() != 255)) {
            basic.clearScreen()
            led.setBrightness(200)
            led.plot(2, 0)
            led.plot(3, 0)
            led.plot(4, 0)
            led.plot(3, 1)
            led.plot(4, 1)
            led.plot(2, 2)
            led.plot(4, 2)
            led.plot(1, 3)
            led.plot(0, 4)
        } else {
            basic.clearScreen()
            led.setBrightness(200)
            basic.showLeds(`
                . . . # #
                # # . . .
                . # . # .
                . . . . .
                . # # # .
                `)
        }
    }
})
